workflows:
  ios-workflow:
    name: Kidsapp iOS Build
    max_build_duration: 60

    environment:
      node: latest

    scripts:
      - name: Install dependencies
        script: npm install

      - name: Install Expo dependencies
        script: npx expo install

      - name: Build Expo export
        script: npx expo export

    artifacts:
      - dist/**

    publishing:
      email:
        recipients:
          - your-email@example.com
